version: '2.1'
services:

    uwsgijup-bit:
      image: uwsgijup:alpine
      build: ./data/dockersrc/bitml
      stop_grace_period: 30s
      depends_on:
        - nginx-bit
      environment:
        - TZ=${TZ}
      volumes:
        - ./data/cfg/uwsgi/:/etc/uwsgi/
        - ./data/cfg/supervisor/supervisord.conf:/etc/supervisord.conf
        - ./data/cfg/jupyter/:/etc/jupyter
        - ./data/app/:/home/alpine/webapp/
      ports:
        - "${HTTP_BIND:-0.0.0.0}:${SUPERVISOR_PORT:-9001}:${SUPERVISOR_PORT:-9001}"
      #  - "${HTTPS_BIND:-0.0.0.0}:${JUPYTER_PORT:-8888}:${JUPYTER_PORT:-8888}"
      #  - "${HTTP_BIND:-0.0.0.0}:${UWSGI_PORTS:-5001-5009}:${UWSGI_PORTS:-5001-5009}"
      restart: always
      dns:
        - ${IPV4_NETWORK:-10.10.10}.254
        - 8.8.8.8
        - 8.8.4.4
      hostname: uwsgijup
      networks:
        bitnet:
          aliases:
            - uwsgijup

    memcached-bit:
      image: memcached:alpine
      restart: always
      dns:
        - ${IPV4_NETWORK:-10.10.10}.254
      networks:
        bitnet:
          aliases:
            - memcached

    redis-bit:
      image: redis:4-alpine
      volumes:
        - redis-vol-1:/data/
      restart: always
      environment:
        - TZ=${TZ}
      dns:
        - ${IPV4_NETWORK:-10.10.10}.254
      networks:
        bitnet:
          ipv4_address: ${IPV4_NETWORK:-10.10.10}.249
          aliases:
            - redis

    phpfpm-bit:
      image: phpfpm:alpine
      build: ./data/dockersrc/phpfpm
      command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
      depends_on:
        - redis-bit
      volumes:
        - ./data/app/phpweb:/web:rw
        - ./data/cfg/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf
        - ./data/cfg/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
        - ./data/cfg/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
        - ./data/cfg/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - BIT_HOSTNAME=${BIT_HOSTNAME}
        - SMTPS_PORT=${SMTPS_PORT:-465}
        - SMTP_PORT=${SMTP_PORT:-25}
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-bit}
      restart: always
      dns:
        - ${IPV4_NETWORK:-10.10.10}.254
      networks:
        bitnet:
          aliases:
            - phpfpm

    nginx-bit:
      depends_on:
        - phpfpm-bit
        - redis-bit
      image: nginx:mainline-alpine
      command: /bin/sh -c "envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active &&
        envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active &&
        envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active &&
        nginx -qt &&
        until ping phpfpm -c1 > /dev/null; do sleep 1; done &&
        until ping redis -c1 > /dev/null; do sleep 1; done &&
        exec nginx -g 'daemon off;'"
      environment:
        - HTTPS_PORT=${HTTPS_PORT:-443}
        - HTTP_PORT=${HTTP_PORT:-80}
        - BIT_HOSTNAME=${BIT_HOSTNAME}
        - IPV4_NETWORK=${IPV4_NETWORK:-10.10.10}
        - TZ=${TZ}
      volumes:
        - ./data/ssl/:/etc/ssl/mail/:ro
        - ./data/app:/home/alpine/webapp:ro
        - ./data/cfg/nginx/:/etc/nginx/conf.d/:rw
      ports:
        - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
      restart: always
      dns:
        - ${IPV4_NETWORK:-10.10.10}.254
      networks:
        bitnet:
          aliases:
            - nginx

networks:
  bitnet:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-10.10.10}.0/24 
          gateway: ${IPV4_NETWORK:-10.10.10}.1
        - subnet: ${IPV6_NETWORK:-fdb5:fbad:3200:800b::/64}
          gateway: fdb5:fbad:3200:800b::1
  #backnet:
  #  driver: custom-driver-1

volumes:
  redis-vol-1:
