version: '2.1'
services:
    portainer-bit:
      image: portainer/portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/cfg/portainer:/data
      restart: always
      dns:
        - ${IPV4_NETWORK:-10.10.10}.254
      dns_search: bitnet
      networks:
        bitnet:
          aliases:
            - portainer
